#!/usr/bin/env bash
# Generate a production .env for the backend-only VPS topology.
#
#   ./deploy/bootstrap-env.sh ftm.altiussystem.com https://app.example.com
#
# Secrets are generated here, on the host that will use them, so they never
# travel through a chat log or a terminal on someone else's machine. Re-running
# refuses to clobber an existing .env — move it aside first if you mean to.
set -euo pipefail

DOMAIN="${1:-}"
# Optional: the dashboard origin is often not known at provisioning time. The
# realm seeds a placeholder, and deploy/set-web-origin.sh edits the client in
# place later — no realm recreation, so deferring this costs nothing.
WEB_ORIGIN="${2:-}"
DEFERRED_ORIGIN=0
if [ -z "$WEB_ORIGIN" ]; then
  WEB_ORIGIN="https://dashboard.invalid"
  DEFERRED_ORIGIN=1
fi

if [ -z "$DOMAIN" ]; then
  cat >&2 <<'USAGE'
usage: deploy/bootstrap-env.sh <api-domain> [dashboard-origin]

  <api-domain>        hostname only, no scheme  e.g. ftm.altiussystem.com
  <dashboard-origin>  full origin with scheme   e.g. https://altius-ftm.vercel.app
                      optional — omit it and a placeholder is used, then run
                      deploy/set-web-origin.sh once the real origin exists.
USAGE
  exit 64
fi

case "$DOMAIN" in
  *://*|*/*) echo "error: <api-domain> must be a bare hostname, got '$DOMAIN'" >&2; exit 64 ;;
esac
case "$WEB_ORIGIN" in
  https://*|http://*) ;;
  *) echo "error: <dashboard-origin> must start with https:// or http://, got '$WEB_ORIGIN'" >&2; exit 64 ;;
esac
# A trailing slash makes Keycloak's redirect comparison fail in a way that is
# tedious to spot: the realm stores "https://x//callback".
WEB_ORIGIN="${WEB_ORIGIN%/}"

cd "$(dirname "$0")/.."
[ -e .env ] && { echo "error: .env already exists — move it aside first" >&2; exit 1; }

gen() { openssl rand -hex 32; }
PG_PASS="$(gen)"; ADMIN_PASS="$(gen)"; AGENT_SECRET="$(gen)"

cat > .env <<EOF
# Generated by deploy/bootstrap-env.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)
# Backend-only VPS topology: api + postgres + keycloak + caddy.
# Used with: docker compose -f docker-compose.yml -f docker-compose.prod.yml

# --- public identity -------------------------------------------------------
ALTIUS_DOMAIN=${DOMAIN}
ALTIUS_WEB_ORIGIN=${WEB_ORIGIN}

# --- secrets (generated on this host) --------------------------------------
POSTGRES_USER=altius
POSTGRES_PASSWORD=${PG_PASS}
POSTGRES_DB=altius
# Must carry the same credentials as above: compose does NOT derive this from
# POSTGRES_PASSWORD, it falls back to a literal postgres://altius:altius@…
DATABASE_URL=postgres://altius:${PG_PASS}@postgres:5432/altius?sslmode=disable

KEYCLOAK_ADMIN=admin
KEYCLOAK_ADMIN_PASSWORD=${ADMIN_PASS}
AGENT_STATE_SECRET=${AGENT_SECRET}
KEYCLOAK_CLIENT_SECRET=

# --- Keycloak wiring -------------------------------------------------------
# The issuer as the BROWSER sees it. The API validates the token's \`iss\`
# claim against this exactly — a token minted via any other hostname is 401.
KEYCLOAK_ISSUER=https://${DOMAIN}/realms/altius

# Internal container routes. Keycloak listens on 8081, not 8080.
KEYCLOAK_JWKS_URL=http://keycloak:8081/realms/altius/protocol/openid-connect/certs
KEYCLOAK_TOKEN_URL=http://keycloak:8081/realms/altius/protocol/openid-connect/token

# The realm's audience mapper emits \`altius-api\`. Anything else here rejects
# every token the realm issues.
KEYCLOAK_AUDIENCE=altius-api
KEYCLOAK_CLIENT_ID=altius-api

KEYCLOAK_REDIRECT_URI=${WEB_ORIGIN}/callback
KEYCLOAK_LOGOUT_REDIRECT_URI=${WEB_ORIGIN}

KEYCLOAK_ADMIN_BASE_URL=http://keycloak:8081
KEYCLOAK_ADMIN_REALM=altius
# Fill these to enable user provisioning from the API (a confidential client
# with realm-management service-account roles). Absent = the endpoint refuses.
KEYCLOAK_ADMIN_CLIENT_ID=
KEYCLOAK_ADMIN_CLIENT_SECRET=

# --- API -------------------------------------------------------------------
STORE_BACKEND=postgres
# Empty denies every cross-origin call, so the dashboard could not reach the API.
CORS_ORIGINS=${WEB_ORIGIN}
ALLOW_PASSWORD_GRANT=false
RUST_LOG=info
LOG_FORMAT=json

DEFAULT_ORG_ID=altius
DEFAULT_ORG_NAME=Altius
DEFAULT_HUB_ID=jakarta
DEFAULT_HUB_NAME=Jakarta
# Placeholder. After the first boot, create the real admin in the Keycloak
# console, copy its user ID (a UUID — that is the JWT \`sub\`), put it here and
# restart the api. Until then that admin gets 403 on every business endpoint.
DEFAULT_ADMIN_SUB=CHANGE-ME-TO-KEYCLOAK-USER-UUID

# --- optional integrations (each off until its key is present) --------------
GOOGLE_MAPS_API_KEY=
GOOGLE_ROUTE_MODE=directions
OPENROUTER_API_KEY=
OPENROUTER_MODEL=openai/gpt-4o-mini
NOTIFY_TOKEN=
NOTIFY_SMS_URL=
NOTIFY_WHATSAPP_URL=
NOTIFY_SENDER=
MCEASY_API_KEY=
EOF

chmod 600 .env
echo "wrote .env (mode 600)"
echo
echo "  API domain        : https://${DOMAIN}"
echo "  Dashboard origin  : ${WEB_ORIGIN}"
echo "  Keycloak issuer   : https://${DOMAIN}/realms/altius"
echo "  Secrets generated : POSTGRES_PASSWORD, KEYCLOAK_ADMIN_PASSWORD, AGENT_STATE_SECRET"
echo
echo "Keycloak console password (needed once, for the first admin):"
echo "  grep KEYCLOAK_ADMIN_PASSWORD .env"
echo
if [ "$DEFERRED_ORIGIN" = "1" ]; then
  echo "NOTE: dashboard origin is a placeholder (${WEB_ORIGIN})."
  echo "      CORS_ORIGINS points at it, so no browser can reach the API yet."
  echo "      When the real origin exists:  ./deploy/set-web-origin.sh https://<origin>"
  echo
fi

echo "Next:"
echo "  ./deploy/preflight.sh"
echo "  docker compose -f docker-compose.yml -f docker-compose.prod.yml up -d --build --wait"
