export const LOCALES = { en: "English", id: "Bahasa Indonesia", th: "ไทย", ja: "日本語", zh: "中文", "fil-PH": "Filipino", vi: "Tiếng Việt" };
export type Locale = keyof typeof LOCALES;
const en = { dashboard: "Overview", tasks: "Tasks", route: "Route planning", flow: "Workflows", data: "Data sources", "import-export": "Import & export", setting: "Settings", billing: "Billing", lhs: "Driver reports", anomaly: "GPS anomalies", search: "Search", create: "Create", save: "Save changes", cancel: "Cancel", all: "All", status: "Status", driver: "Driver", hub: "Hub", demo: "Demo workspace", signIn: "Enter demo workspace", task: "Task board", tracking: "Tracking", schedule: "Schedules", gallery: "Gallery", visit: "Visits", configuration: "Configuration", result: "Route results", automation: "Automation", workflow: "Sequences", "data-list": "Customers", "data-type": "Data types", "data-import": "Import data", "data-export": "Export data", user: "Users", team: "Teams", permission: "Permissions", organization: "Organization", "custom-module": "Custom modules", trash: "Trash", plan: "Plans", subscription: "Subscription", history: "Invoices", "no-access": "Add-ons", completed: "Completed", assigned: "Assigned", unassigned: "Unassigned", "in-progress": "In progress", failed: "Failed", empty: "No matching records", reset: "Reset filters", export: "Export CSV" };
export type TranslationKey = keyof typeof en;
const dictionaries: Record<Exclude<Locale, "en">, Partial<Record<TranslationKey, string>>> = {
  id: { dashboard: "Dasbor", tasks: "Tugas", route: "Perencanaan rute", flow: "Alur kerja", data: "Sumber data", "import-export": "Impor & ekspor", setting: "Pengaturan", billing: "Penagihan", lhs: "Laporan harian sopir", anomaly: "Anomali GPS", search: "Cari", create: "Buat", save: "Simpan perubahan", cancel: "Batalkan", all: "Semua", status: "Status", driver: "Sopir", hub: "Hub", demo: "Ruang kerja demo", signIn: "Masuk ruang kerja demo", task: "Daftar tugas", tracking: "Pelacakan", schedule: "Jadwal", gallery: "Galeri", visit: "Kunjungan", configuration: "Konfigurasi", result: "Hasil rute", automation: "Otomatisasi", workflow: "Rangkaian kerja", "data-list": "Pelanggan", "data-type": "Tipe data", "data-import": "Impor data", "data-export": "Ekspor data", user: "Pengguna", team: "Tim", permission: "Hak akses", organization: "Organisasi", "custom-module": "Modul kustom", trash: "Sampah", plan: "Paket", subscription: "Berlangganan", history: "Faktur", completed: "Selesai", assigned: "Ditugaskan", unassigned: "Belum ditugaskan", "in-progress": "Berjalan", failed: "Gagal", empty: "Data tidak ditemukan", reset: "Atur ulang filter", export: "Ekspor CSV" },
  th: { dashboard: "ภาพรวม", tasks: "งาน", route: "วางแผนเส้นทาง", flow: "เวิร์กโฟลว์", data: "แหล่งข้อมูล", "import-export": "นำเข้าและส่งออก", setting: "การตั้งค่า", billing: "การเรียกเก็บเงิน", lhs: "รายงานคนขับ", anomaly: "ความผิดปกติ GPS", search: "ค้นหา", create: "สร้าง", save: "บันทึก", cancel: "ยกเลิก", demo: "พื้นที่สาธิต", signIn: "เข้าสู่การสาธิต", completed: "เสร็จสิ้น", status: "สถานะ", driver: "คนขับ", all: "ทั้งหมด" },
  ja: { dashboard: "概要", tasks: "タスク", route: "ルート計画", flow: "ワークフロー", data: "データソース", "import-export": "インポート・エクスポート", setting: "設定", billing: "請求", lhs: "ドライバー日報", anomaly: "GPS異常", search: "検索", create: "作成", save: "変更を保存", cancel: "キャンセル", demo: "デモワークスペース", signIn: "デモを開始", completed: "完了", status: "ステータス", driver: "ドライバー", all: "すべて" },
  zh: { dashboard: "总览", tasks: "任务", route: "路线规划", flow: "工作流程", data: "数据源", "import-export": "导入与导出", setting: "设置", billing: "账单", lhs: "司机日报", anomaly: "GPS异常", search: "搜索", create: "创建", save: "保存更改", cancel: "取消", demo: "演示工作区", signIn: "进入演示", completed: "已完成", status: "状态", driver: "司机", all: "全部" },
  "fil-PH": { dashboard: "Pangkalahatan", tasks: "Mga gawain", route: "Pagpaplano ng ruta", flow: "Daloy ng trabaho", data: "Mga pinagmulan ng datos", "import-export": "Mag-import at mag-export", setting: "Mga setting", billing: "Pagsingil", lhs: "Ulat ng drayber", anomaly: "Anomalya sa GPS", search: "Maghanap", create: "Gumawa", save: "I-save", cancel: "Kanselahin", demo: "Demo workspace", signIn: "Pumasok sa demo", completed: "Tapos na", status: "Katayuan", driver: "Drayber", all: "Lahat" },
  vi: { dashboard: "Tổng quan", tasks: "Nhiệm vụ", route: "Lập kế hoạch tuyến", flow: "Quy trình", data: "Nguồn dữ liệu", "import-export": "Nhập và xuất", setting: "Cài đặt", billing: "Thanh toán", lhs: "Báo cáo tài xế", anomaly: "Bất thường GPS", search: "Tìm kiếm", create: "Tạo", save: "Lưu thay đổi", cancel: "Hủy", demo: "Không gian demo", signIn: "Vào bản demo", completed: "Hoàn thành", status: "Trạng thái", driver: "Tài xế", all: "Tất cả" }
};
export const translate = (locale: Locale, key: string): string => (locale !== "en" ? dictionaries[locale][key as TranslationKey] : undefined) ?? en[key as TranslationKey] ?? key;
export const formatNumber = (locale: Locale, value: number) => new Intl.NumberFormat(locale === "fil-PH" ? "fil" : locale).format(value);
